# Kubespray inventory — devops-class-2601 (HA: 3 controllers + 1 worker)
# Update ansible_host and ip after each terraform apply

[all]
# control plane nodes — run etcd + kube-apiserver + scheduler + controller-manager
controller-1 ansible_host=18.143.165.30   ip=172.31.82.177  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

# worker node — runs workloads only
worker       ansible_host=47.128.214.85 ip=172.31.89.67  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube_control_plane]
controller-1


[etcd]
# etcd runs as systemd service on all control plane nodes
controller-1


[kube_node]
worker

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
