[all]
controller ansible_host=54.255.211.67  ip=172.31.95.70  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
worker     ansible_host=54.169.186.251 ip=172.31.86.170 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube_control_plane]
controller

[etcd]
controller

[kube_node]
worker

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
