# Kubespray inventory — devops-class-2601 (HA: 3 controllers + 1 worker)
# Update ansible_host and ip after each terraform apply

[all]
# control plane nodes — run etcd + kube-apiserver + scheduler + controller-manager
controller-1 ansible_host=13.250.6.216   ip=172.31.84.23  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
controller-2 ansible_host=54.251.213.170 ip=172.31.92.50  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
controller-3 ansible_host=13.229.211.61  ip=172.31.84.214 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

# worker node — runs workloads only
worker       ansible_host=13.229.200.215 ip=172.31.90.75  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube_control_plane]
controller-1
controller-2
controller-3

[etcd]
# etcd runs as systemd service on all control plane nodes
controller-1
controller-2
controller-3

[kube_node]
worker

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
